argocd-apps:
  applications:
    example-app:
      namespace: argocd  # namespace у Kubernetes
      project: default    #  назва Argo CD проєкту
      source: # джерело коду застосунку
        repoURL: https://github.com/Sysqwerty/devops.git
        path: charts/django-app     # шлях усередині репозиторію до потрібного чарта або YAML-файлів
        targetRevision: lesson-10    # гілка або тег Git, з якого брати застосунок (наприклад, main)
        helm:
          valueFiles: # перелік YAML-файлів із налаштуваннями, які будуть передані Helm-чарту
            - values.yaml
      destination: # вказує, куди саме деплоїти застосунок
        server: https://kubernetes.default.svc  # адреса Kubernetes API-сервера. Для внутрішнього кластера використовується https://kubernetes.default.svc
        namespace: default                      # Kubernetes namespace для цього конкретного застосунку
      syncPolicy: # політика синхронізації
        automated: # включає автоматичне застосування змін
          prune: true       # видаляти ресурси, які більше не описані у Git
          selfHeal: true    # автоматично виправляти відхилення від Git-стану, якщо щось змінилось вручну у кластері

  repositories:
    example-app:
      url: https://github.com/Sysqwerty/devops.git

  repoConfig:
    insecure: "true"    # дозволяє підключення до репозиторію без перевірки SSL-сертифікатів. Не рекомендується для продакшену
    enableLfs: "true"   # дозволяє використання Git LFS (Large File Storage), якщо в репозиторії зберігаються великі файли